---
title: "2. SMP 데이터 병합하기"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
---

# 패키지 로드
```{r, message = FALSE}
# general visualisation
library(needs)
needs(tidyverse,scales,grid,gridExtra,RColorBrewer,corrplot,readr,stringr,
        data.table,tibble,tidyr,stringr,forcats,lubridate,ggforce,ggridges)
```

# rec, smp 데이터 로드
```{r}
rec <- read_csv("../data_all/REC_jiseung_pretreatment.csv")
rec$date_ym <-str_sub(rec$date,1,6)
smp <- read_csv("../data_all/mean_SMP.csv")
smp$date <- as.numeric(gsub("-","",as.Date(smp$date,"%Y.%m.%d")))
smp$date_ym <- str_sub(smp$date,1,6)
smp <- smp %>% select(-date)
```

# 최근 smp 데이터 가져오기
```{r}
smp_in <- read_csv("../data_all/smp_in.csv")
smp_in$date <- as.numeric(gsub("-","",as.Date(smp_in$date,"%Y/%m/%d")))
smp_in$date_ym <- str_sub(smp_in$date,1,6)
smp_in_ym <- smp_in %>% group_by(date_ym) %>% summarise(mean_smp = mean(mean_smp))
smp_in_ym <- smp_in_ym[-c(1,2,3,4),]
colnames(smp_in_ym) <- c("date_ym","SMP_in")
smp_out <- read_csv("../data_all/smp_out.csv")
smp_out$date <- as.numeric(gsub("-","",as.Date(smp_out$date,"%Y/%m/%d")))
smp_out$date_ym <- str_sub(smp_out$date,1,6)
smp_out_ym <- smp_out %>% group_by(date_ym) %>% summarise(mean_smp = mean(mean_smp))
smp_out_ym <- smp_out_ym[-c(1,2,3,4),]
colnames(smp_out_ym) <- c("date_ym","SMP_out")
smp_plus <- smp_in_ym %>% inner_join(smp_out_ym)
smp <- smp %>% bind_rows(smp_plus) 
smp <- smp %>% arrange(date_ym)
```

# rec, smp 병합
```{r}
result <- rec %>% left_join(sm기p)
result <- result %>% select(-date_ym)
result$SMP <- result %>% with(ifelse(location_in==1&location_out==1,SMP_inout,0))
result$SMP <- result %>% with(ifelse(location_in==0&location_out==1,SMP_out,SMP))
result$SMP <- result %>% with(ifelse(location_in==1&location_out==0,SMP_in,SMP))
result <- result %>% select(-SMP_in,-SMP_out,-SMP_inout)
summary(result)
# write.csv(result,"REC_SMP.csv",row.names=FALSE)
```

# rec 데이터에 최대 최소 가격 추가
```{r}
rec <- read_csv("../data_need/REC_SMP.csv")

rec_final_price <- read_csv("../data_all/rec_final_price.csv")

rec_final_price <- bind_cols(date=c(rec_final_price$date,0),
                             final_price=c(rec_final_price$final_price,0),
                             before_final_price=c(0,rec_final_price$final_price))

rec <- rec %>% left_join(rec_final_price)

rec <- rec %>% mutate(allow_max_price = before_final_price*1.3,
                          allow_min_price = before_final_price*0.7)

# write.csv(rec,"../data_need/REC_SMP.csv",row.names = FALSE)
```


