---
title: "5. 데이터 시각화"
date: '`r Sys.Date()`'
output:
  html_document:
    number_sections: true
    fig_caption: true
    toc: true
    fig_width: 7
    fig_height: 4.5
    theme: cosmo
    highlight: tango
editor_options: 
  chunk_output_type: inline
---

# 패키지 로드
```{r, message = FALSE}
# general visualisation
library(needs)
needs(tidyverse,scales,grid,gridExtra,RColorBrewer,corrplot,readr,stringr,
        data.table,tibble,tidyr,stringr,forcats,lubridate,ggforce,ggridges)
```

# 2012-01-01 이후 데이터 로드
```{r}
total <- read.csv("../data_need/jiseung_20120101_20171130.csv")
```

# 변수 EDA
```{r}
summary(total)
```

## REC 가격

http://www.knrec.or.kr/knrec/index.asp

```{r}
rec <- total %>% select(date,price,SMP,type)

ggplot(data=rec, aes(x=ymd(date),y = price,color=type)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) +
  labs(y="price",x="date")+ geom_vline(xintercept = ymd(20150510))+ 
  geom_vline(xintercept = ymd(20160220))+ 
  geom_vline(xintercept = ymd(20170328))
```


## smp 가격

http://epsis.kpx.or.kr/epsisnew/selectEkmaSmpShdGrid.do?menuId=050202

```{r}
ggplot(data=rec, aes(x=ymd(date),y = SMP,color=type)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) +
  labs(y="price",x="date")+ geom_vline(xintercept = ymd(20150510))+ 
  geom_vline(xintercept = ymd(20160220))+ 
  geom_vline(xintercept = ymd(20170328))
```


- 정책이 달라지는 시기


| date              | energy      | location | 
| ----------------- | ----------- | -------- |
| 20120228~20150508 | General/Sun | Total    |
| 20150513~20160217 | General/Sun | In/Out   | 
| 20160304~20171128 | Total       | In/Out   |

# 2016-03-04 이후 데이터 로드
```{r}
total <- read.csv("../data_need/jiseung_20160304_20171130.csv")
```

# 변수 EDA
```{r}
summary(total)
```

## REC 가격

http://www.knrec.or.kr/knrec/index.asp

```{r}
rec <- total %>% select(date,price,SMP,type)

ggplot(data=rec, aes(x=ymd(date),y = price,color=type)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) +
  labs(y="price",x="date")+ facet_wrap(~ type)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


## smp 가격

http://epsis.kpx.or.kr/epsisnew/selectEkmaSmpShdGrid.do?menuId=050202

```{r}
ggplot(data=rec, aes(x=ymd(date),y = SMP,color=type)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) +
  labs(y="price",x="date") + facet_wrap(~ type)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

SMP 가격이 높아지면서 REC 가격 상승(최근) 

최근 신재생에너지 투자가 인기가 많아지면서 투자자가 몰려 발전량 자체가 많아졌다 => REC가격의 하락


## 물가지수 

http://data.seoul.go.kr/openinf/linkview.jsp?infId=OA-11716

```{r}
Prices1  <- total %>% select(1,which(colnames(total) == "생활물가지수"):(which(colnames(total) == "생활물가지수")+4))
Prices1 <- melt(Prices1, id.vars = "date")
Prices1$value <- Prices1$value %>% as.numeric()

Prices1 %>% 
  ggplot(aes(x=ymd(date),y = value,color=variable)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d"))   + 
  labs(y="물가지수",x="date")+ facet_wrap(~ variable)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
Prices2 <- total %>% select(1,which(colnames(total) == "생활물가지수_up"):(which(colnames(total) == "생활물가지수_up")+4))
Prices2 <- melt(Prices2, id.vars = "date")
Prices2$value <- Prices2$value %>% as.numeric()

Prices2 %>% 
  ggplot(aes(x=ymd(date),y = value,color=variable)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d"))   + 
  labs(y="연료단가",x="date") + facet_wrap(~ variable)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```


## 전라남도 날씨 데이터

http://www.kweather.co.kr/main/main.html

```{r}
total  %>% select(1,which(colnames(total) == "구름많음"):(which(colnames(total) == "구름많음")+5)) %>% melt(id.vars = "date") %>%
  ggplot(aes(x=ymd(date),y = value,color=variable)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d"))   + 
  labs(y="날씨",x="date") + facet_wrap(~ variable)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r}
total %>% select(1,which(colnames(total) == "min_Temperature_sum"):(which(colnames(total) == "min_Temperature_sum")+3)) %>% 
  melt(id.vars = "date") %>%
  ggplot(aes(x=ymd(date),y = value,color=variable)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d"))   + 
  labs(y="mm,temperature",x="date") + facet_wrap(~ variable)+ theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## 원유

http://www.opinet.co.kr/glopcoilSelect.do#

```{r}
Oil <- total %>% select(1,which(colnames(total) == "Dubai"):(which(colnames(total) == "Dubai")+2)) %>% subset(Dubai!=0 & WTI!=0)
Oil1 <- melt(Oil, id.vars = "date")
Oil1$value <- Oil1$value %>% as.numeric()

Oil1 %>% 
  ggplot(aes(x=ymd(date),y = value,color=variable)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d"))   + 
  labs(y="price",x="date")+ facet_wrap(~ variable) + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## 연말 변수

연말로 향할수록 RPS 불이행을 최소화하기 위해 가격이 오른 이력이 있다.

```{r}
total %>% 
  ggplot(aes(x=ymd(date),y = date_end)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) + 
  labs(y="date_end",x="date")
```

## 정부정책

정부가 신재생에너지 생산량을 보호하기 위해 만든 시장이기 때문에 정부의 정책에 따라 크게 휘둘린다.

```{r}
total %>% 
  ggplot(aes(x=ymd(date),y = agenda1)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) + 
  labs(y="agenda",x="date")
```

## 이전 거래량 
```{r}
total %>% 
  ggplot(aes(x=ymd(date),y = before_count)) + 
  geom_line() +
  scale_x_date(labels = date_format("%Y-%m-%d")) + 
  labs(y="before_count",x="date")
```