---
title: "6. 전체 기간 데이터 병합 & 모델링"
author: "jiseungRyu"
date: '2017 11 27 '
output: html_document
---
###### Load libraries and helper functions
```{r, message = FALSE}
# general visualisation
library(needs)
needs(tidyverse,scales,grid,gridExtra,RColorBrewer,corrplot,readr,stringr,
        data.table,tibble,tidyr,stringr,forcats,lubridate,ggforce,ggridges,
      caret,party,e1071,kknn,nnet,gbm,pls,randomForest,glmnet)
```

#### REC 가격

http://www.knrec.or.kr/knrec/index.asp

```{r}
rec <- read_csv("../data_need/REC_SMP.csv")

rec$date_ym <- substr(rec$date,1,6) %>% as.numeric()
```


#### 물가지수(20171101까지 자료존재)

http://data.seoul.go.kr/openinf/linkview.jsp?infId=OA-11716

```{r}
Prices  <- read_csv("../data_need/물가.csv")[-72,]
Prices$date <- Prices %>% with(ifelse(nchar(Prices$date)==6,paste0(date,"0.01"),paste0(date,".01")))
Prices$date <- gsub("-","",as.Date(Prices$date,"%Y.%m.%d"))

Prices$생활물가지수_up <- c(1,diff(Prices$생활물가지수))/Prices$생활물가지수
Prices$식품_up <- c(1,diff(Prices$식품))/Prices$식품
Prices$식품_이외_up <- c(1,diff(Prices$식품_이외))/Prices$식품_이외
Prices$전월세_up <- c(1,diff(Prices$전월세))/Prices$전월세
Prices$전월세포함_생활물가지수_up <- c(1,diff(Prices$전월세포함_생활물가지수))/Prices$전월세포함_생활물가지수

Prices$date_ym <- substr(Prices$date,1,6) %>% as.numeric()
Prices <- Prices %>% select(-date)
```


#### 원유(2016/3)

http://www.opinet.co.kr/glopcoilSelect.do#

```{r}
Oil <- read.table("../data_need/National_OIL.csv",sep=",",header=TRUE)
colnames(Oil)[1] <- "date"
Oil$date <- gsub("_","",Oil$date)
Oil$date <- paste0("20",Oil$date) %>% as.numeric()
```


#### 연말 변수 : 연말로 향할수록 RPS 불이행을 최소화하기 위해 가격이 오른 이력이 있다.

```{r}
total <- rec %>%  left_join(Prices,by="date_ym") %>% left_join(Oil,by="date")

total$date_end <- ifelse(substr(total$date,5,6) %>% as.numeric() >= 12,1,0)
total$before_count <- c(1,total$count[-377])
```


#### 정부정책 : 정부가 신재생에너지 생산량을 보호하기 위해 만든 시장이기 때문에 정부의 정책에 따라 크게 휘둘린다. Ex) 과징금, 통합 시장 이후 태양광 의무공급량 제한 해제, 정부의 신재생에너지 20%확대 정책 등????
```{r}
total$agenda1 <- ifelse(total$date %in% c(20150508,20150513,20160217,20160304,20170315,20170328),1,0)

total$agenda1 <- ifelse(total$date>=20171100 & total$date<20171230,1,total$agenda1)
```


------------------


### train, test set 나누기
```{r}
total_train <- total %>% subset(date<=20170100) %>%
                          select(-date_ym,-type,-count,-max_price,-min_price)

total_test <- total %>% subset(date>20170100  & date<=20171200) %>% 
                          select(-date_ym,-type,-count,-max_price,-min_price)

```



------------------


### 1.Regression
```{r}
# total_train <- total_train %>% select(-pred)
# total_test <- total_test %>% select(-pred)
summary(total)
summary(lm.fit.in<-lm(price ~ . ,data=total_train %>% select(-date)))

total_train$pred <- predict(lm.fit.in,total_train)
total_test$pred <- predict(lm.fit.in,total_test)

total_s <- total_train %>% bind_rows(total_test)
total_s %>% select(date,price,pred) %>% ggplot(aes(x=ymd(date),y=price))+
  geom_point(color="black") + geom_point(aes(y=pred),color="red") + geom_vline(xintercept = ymd(20170101))

sqrt(mean((total_train$pred - total_train$price)^2))
sqrt(mean((total_test$pred - total_test$price)^2))
```


------------------

#### 2.RandomForest 
```{r}
total_train <- total_train %>% select(-pred)
total_test <- total_test %>% select(-pred)
rf<-randomForest(price~. ,total_train %>% select(-date),ntree=30,importance=T)
plot(rf)

#가장 큰 영향력 있는 변수가 맨 위에 온다.
var.imp<-data.frame(importance(rf,type=2))
#importance는 지니계수 사용한 것임.
var.imp$Variables <- row.names(var.imp)
var.imp[order(var.imp$IncNodePurity,decreasing = T),]

total_train$pred <- predict(rf,total_train)
total_test$pred <- predict(rf,total_test)

total_s <- total_train %>% bind_rows(total_test)
total_s %>% select(date,price,pred) %>% ggplot(aes(x=ymd(date),y=price))+
  geom_point(color="black") + geom_point(aes(y=pred),color="red") + geom_vline(xintercept = ymd(20170101))

sqrt(mean((total_train$pred - total_train$price)^2))
sqrt(mean((total_test$pred - total_test$price)^2))

```


------------------

####  3.KNN
```{r}
total_train <- total_train %>% select(-pred)
total_test <- total_test %>% select(-pred)

knn.fit_train<-kknn(price ~ ., train = total_train %>% select(-date), test = total_train)
knn.fit_test<-kknn(price ~ ., train = total_train %>% select(-date), test = total_test)

total_train$pred <- fitted(knn.fit_train)
total_test$pred <- fitted(knn.fit_test)

total_s <- total_train %>% bind_rows(total_test)
total_s %>% select(date,price,pred) %>% ggplot(aes(x=ymd(date),y=price))+
  geom_point(color="black") + geom_point(aes(y=pred),color="red") + geom_vline(xintercept = ymd(20170101))

sqrt(mean((total_train$pred - total_train$price)^2))
sqrt(mean((total_test$pred - total_test$price)^2))

```


------------------

####  4. Neuralnet
```{r}
total_train <- total_train %>% select(-pred)
total_test <- total_test %>% select(-pred)

INPUT_NODES<-10
HIDDEN_NODES<-INPUT_NODES*2
OUTPUT_NODES<-5
ITERATION<-100

nnet_md<-nnet(formula = price~. ,data= total_train %>% select(-date),size=5,linout = TRUE,rang = 0.1,skip=TRUE,maxit = ITERATION)
#sizt=은닉층 노드 수
#linout=FALSE 모델 학습 시 모델의 출력과 원하는 값을 비교할 때 사용할 함수. TRUE면 엔트로피,FALSE면 SSE가 사용된다.
#skip:입력변수가 출력변수로 은닉층 없이 연결되는지 여부, 직접 연결시 T
#rang : 가중치의 초기값이 없다면 임의로 초기값 정함, (n, -rang, rang)
#maxit : 훈련 최적화를 위한 반복횟수

#모델완성
total_train$pred<-predict(nnet_md,total_train,type="raw")
total_test$pred<-predict(nnet_md,total_test,type="raw")

total_s <- total_train %>% bind_rows(total_test)
total_s %>% select(date,price,pred) %>% ggplot(aes(x=ymd(date),y=price))+
  geom_point(color="black") + geom_point(aes(y=pred),color="red") + geom_vline(xintercept = ymd(20170101))

sqrt(mean((total_train$pred - total_train$price)^2))
#RMSE : 9221.441
sqrt(mean((total_test$pred - total_test$price)^2))
#RMSE : 30056.89
```


------------------

####  5. Boosting
```{r}
total_train <- total_train %>% select(-pred)
total_test <- total_test %>% select(-pred)

boosting <- gbm(price~., data = total_train %>% select(-date),
                distribution = "gaussian",
                n.trees = 10000)


#모델완성
total_train$pred<-predict(boosting,total_train,n.trees=10000)
total_test$pred<-predict(boosting,total_test,n.trees=10000)

total_s <- total_train %>% bind_rows(total_test)
total_s %>% select(date,price,pred) %>% ggplot(aes(x=ymd(date),y=price))+
  geom_point(color="black") + geom_point(aes(y=pred),color="red") + geom_vline(xintercept = ymd(20170101))

sqrt(mean((total_train$pred - total_train$price)^2))
#RMSE : 9284.868
sqrt(mean((total_test$pred - total_test$price)^2))
#RMSE : 11823.42
```



[추가적으로 보고 싶은 것]

1. http://blog.solarconnect.kr/221149950976

2. 내년에 REC 의무할당량 2배 증가

3. 신재생에너지 3020 로드맵 : http://www.mega-solar.co.kr/bbs/content.php?co_id=project02